name: deencastv2
description: "An islamic audio posdcast app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


#--- PACKAGES --- #
dependencies:
  flutter:
    sdk: flutter

#    UTILITY PACKAGES
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  lottie: ^3.3.1
  auto_size_text: ^3.0.0
  hijri_calendar: ^1.0.7
  just_audio: ^0.9.39

#  ICONS
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

#STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1

#--- END PACKAGES---#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

#App icon
flutter_launcher_icons:
  android: true
  ios: "AppIcon"
  image_path: "assets/logo/Deen_cast_logo_3.PNG"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/onboarding/
     - assets/logo/
     - assets/socials/
     - assets/scholars/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
